### ISSUE TITLE
Changing zoom level messes up dragging on canvas

### ISSUE THREAD

**Issue by davidkutas** [ceddlyburge/react-figma-miro-canvas-part-3#1]
Changing the zoom level makes the dragging of elements inaccurate. Meaning, that you drag an element that is already on the canvas, and when you release it it jumps to another location.

Is there a way to fix it?

**Comment by ceddlyburge** [comment]
Oooops, I must have done a bad copy and paste there. I thought I had checked this all thoroughly but obviously not. Anyway, its working now.
