### ISSUE TITLE
Noice!

### ISSUE THREAD

**Issue by iaverypadberg** [ceddlyburge/react-figma-miro-canvas-part-3#3]
Thanks for writing and publishing this code- super well done and performant. I was hacking around with the react-rnd libary and had little success. (˶ᵔ ᵕ ᵔ˶)

**Comment by ceddlyburge** [comment]
Awesome, glad you like it!

This code is as simple as possible, to make the blog post easy to understand, but there are some further performance things you can do. The easy ones are memo and useCallback and stuff like that, and we use some weird css in production to avoid react re renders, and I'm sure there are more things you could do if you dig deeper and need the performance. We didn't need to though.

Anyway, there is some discussion of performance in #2 if you ever need it.

Cheers, Cedd
